### PR TITLE
feat: cleanup HTML file

### PR DESCRIPTION
**Pull request by LaansDole**
I delete the script inside the HTML and add a bit of styling for the background, it was quite bright

### CODE REVIEW

**Comment by SchBenedikt** [comment]
image

And now I can delete that because I took your code to my main branch?
Sorry for the question, but I don't have that much experience with this yet!

**Comment by LaansDole** [comment]
Your very much welcome, Benedikt. You can also close my branch, by the way, can you check your email, I have something to discuss with you and ofc not over github

**Comment by SchBenedikt** [comment]
I will answer you via email as soon as possible @LaansDole

**Comment by SchBenedikt** [comment]
Now I had time and answered you by mail!

**Pull request merged**
