### PR TITLE
 Changes to be committed:

### PR DESCRIPTION
**Pull request by ShafiMohammad09**
I've made some changes:

- Modified: index.html
- Modified: style.css

I added a pale glassmorphism effect. However, it seems that the profile picture section isn't functioning as expected from the beginning. It might be a good idea to assign someone to look into it.

Anyhow, I hope you like the UI. This is my contribution to the project. Wishing you all the best with your continued work!

Please note that there are still some font styling modifications that need to be made. Unfortunately, I'm currently unable to work on them.

image

### CODE REVIEW

**Review by LaansDole — APPROVED** [review]
It looks very good and aesthetically pleasing, good job

**Comment by SchBenedikt** [comment]
I think it looks pretty great, but there are still a few problems (font, or image below.)
image

**Comment by ShafiMohammad09** [comment]
Thank you for pointing out the issues @SchBenedikt . I'll make the necessary adjustments. Once this PR is successfully merged, I'll be glad to address any remaining concerns in a new PR. Additionally, I'm open to any further suggestions you may have. Your feedback is highly appreciated! @LaansDole

**Comment by ShafiMohammad09** [comment]
hello bro @SchBenedikt merge this "PR" so that i can work on the " New PR "

**Comment by SchBenedikt** [comment]
@ShafiMohammad09 How's the new PR coming along?

**Comment by SchBenedikt** [comment]
#36 Read this for more information!

**Pull request merged**
