### PR TITLE
Improved the projects tab

### PR DESCRIPTION
**Pull request by MarvinTMavee**
- Moved the search project bar to the top of all the projects for a better overview
- Added a minimum width to the projects (This is important when only showing one project since it will shrink for some reason)

### CODE REVIEW

**Comment by SchBenedikt** [comment]
NEW DESIGN
image



OLD DESIGN
image

**Comment by SchBenedikt** [comment]
Maybe this can be improved too? Since you usually view it on the desktop anyway, it would also fit that way.

**Review by SchBenedikt — COMMENTED** [review]
See my comments!

**Comment by MarvinTMavee** [comment]
Hey. I think I can fix this later this day. The problem that I was trying to fix it was that the size was reduced for some reason when searching for a project (See screenshot)
Bildschirmfoto 2024-01-24 um 14 19 54

**Pull request merged**
